webhook-url: ""
webhook-name: ""
# ---------------------

Message:
  chat-message: true
  title: "[ğŸ’¬] New Message"
  content: "{Player} : "

Leave:
  on-leave: true
  title: "[â–] New Leave"
  content: "{Player} a quittÃ© le serveur"

Death:
  on-death: true
  title: "[ğŸ’€] New Death"
  content: "{Player} est mort"

Join:
  on-join: true
  title: "[â•] Join"
  content: "{Player} a rejoint le serveur"

Command:
  on-command: true
  title: "[âš™ï¸] New Command"
  content: "{Player} a exÃ©cutÃ© la commande : /"

Death-Entity:
  on-death-entity: false
  title: "[â˜ ï¸] New Death Entity"
  content: "{Entity} est mort(e) dans le monde :"

Give:
  on-give: true
  title: "[ğŸ’] New give command"
  content: "{Player} a exÃ©cutÃ© la commande : /"

